import asyncio
from datetime import datetime, timezone

# Adjust these imports based on your actual project structure
from workers.attention_worker import AttentionWorker

class MockSummarizer:
    """A fake summarizer to test the worker without hitting the real AI API."""
    
    async def add_task(self, task_data):
        print("\n" + "="*50)
        print("🤖 [MockSummarizer] RECEIVED PROMPT FROM JINJA:")
        print("="*50)
        print(task_data["data"])
        print("="*50 + "\n")
        
        # Create a dummy async function to simulate the 'beeper'
        async def beeper():
            print("[MockSummarizer] Simulating API delay (1 second)...")
            await asyncio.sleep(1) 
            
            # Return a fake summary structure that matches what the worker expects
            return {
                "summaries": {
                    "80": "Auto-Generated Test Name",
                    "200": "This is a short summary generated by the Mock. Everything is working!",
                    "600": "This is a detailed summary generated by the Mock. The template rendered perfectly."
                }
            }
            
        return beeper()


async def main():
    print("🚀 Starting AttentionWorker Test...")
    
    # 1. Initialize our mock agent and the worker
    mock_summarizer = MockSummarizer()
    worker = AttentionWorker(summarizer=mock_summarizer)
    
    # 2. Prepare the task data
    # IMPORTANT: You must replace these with actual IDs that exist in your database right now!
    test_attention_id = "PUT_A_REAL_ATTENTION_ID_HERE" 
    test_session_id = "PUT_A_REAL_SESSION_ID_HERE"
    
    # Generate a real ISO timestamp for right now
    current_time = datetime.now(timezone.utc).isoformat()
    
    task_data = {
        "attention_id": test_attention_id,
        "session_id": test_session_id,
        "timestamp": current_time
    }
    
    print(f"\n📦 Sending task to worker:")
    print(f"Attention ID: {task_data['attention_id']}")
    print(f"Session ID:   {task_data['session_id']}")
    print(f"Timestamp:    {task_data['timestamp']}\n")
    
    # 3. Run the process!
    updated_record = await worker.process_task(task_data)
    
    # 4. Check the results
    print("\n🏁 --- TEST COMPLETE ---")
    if updated_record:
        print("✅ Success! Updated Record from DB:")
        print(f"Name: {updated_record.get('name')}")
        print(f"Short Summary: {updated_record.get('short_summary')}")
    else:
        print("❌ Worker returned None. Double-check if the IDs you provided actually exist in the DB.")

if __name__ == "__main__":
    # Run the async main loop
    asyncio.run(main())