import unreal
import socket

server_socket = None
tick_handle = None

def start_server():
    global server_socket
    if server_socket:
        try:
            server_socket.close()
        except:
            pass
            
    server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    server_socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    # UEFN uses port 9998
    server_socket.bind(('127.0.0.1', 9998))
    server_socket.listen(1)
    server_socket.setblocking(False)
    unreal.log("nBaya UEFN Server is listening on port 9998...")

def listen_for_commands(delta_time):
    global server_socket
    if server_socket is None:
        return

    try:
        conn, addr = server_socket.accept()
        conn.setblocking(True) 
        
        data = conn.recv(4096).decode('utf-8')
        command = data.strip()

        if command.startswith("EXECUTE_CODE:"):
            script_content = command[len("EXECUTE_CODE:"):].strip()
            try:
                # Catch variables generated by the AI script
                local_vars = {}
                exec(script_content, globals(), local_vars)
                
                # If a 'result' variable was created, send it back
                if 'result' in local_vars:
                    response_data = str(local_vars['result'])
                    conn.send(response_data.encode('utf-8'))
                else:
                    conn.send('{"success": true, "message": "Code executed.", "data": {}}'.encode('utf-8'))
            except Exception as e:
                # Log the error in UEFN and send it back to the AI
                error_msg = f'{{"success": false, "message": "Execution error: {e}", "data": []}}'
                unreal.log_error(error_msg)
                conn.send(error_msg.encode('utf-8'))
                
        conn.close()
        
    except BlockingIOError:
        pass
    except Exception as e:
        pass

def register():
    global tick_handle
    start_server()
    if tick_handle:
        try:
            unreal.unregister_slate_post_tick_callback(tick_handle)
        except:
            pass
    tick_handle = unreal.register_slate_post_tick_callback(listen_for_commands)

if __name__ == "__main__":
    register()